version: '3'
services:
  portainer:
    image: portainer/portainer-ce
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --logo https://logodetimes.com/times/flamengo/logo-flamengo-antigo-2048.png
